;; ---------------------------------------------------------------------------
;; AUTO-GENERATED by make_dll_runtime_thunks.py
;; Do not edit manually.
;; ---------------------------------------------------------------------------
bits 32

section .text

extern _dbm_runtime_proc_table

global _jit_dynarray_setlength
global _jit_read_int
global _jit_read_string
global _jit_blake2
global _jit_crc16
global _jit_crc32
global _jit_crc32c
global _jit_crc64
global _jit_md5
global _jit_sha1
global _jit_sha3
global _jit_sha224
global _jit_sha256
global _jit_sha384
global _jit_sha512
global _jit_debug_break
global _jit_disk_free
global _jit_disk_total
global _jit_disk_label
global _jit_disk_serial
global _jit_disk_filesystem
global _jit_disk_type
global _jit_disk_share
global _jit_disk_used
global _jit_disk_exists
global _jit_disk_ready
global _jit_disk_is_cdrom
global _jit_disk_is_network
global _jit_disk_is_removable
global _jit_disk_is_fixed
global _jit_error_runtime
global _jit_error_array_bounds
global _jit_error_string_range
global _jit_error_nil_pointer
global _jit_error_out_of_memory
global _jit_exception_push
global _jit_exception_pop
global _jit_setjmp
global _jit_longjmp
global _jit_memcpy
global _jit_memset
global _jit_memcmp
global _jit_memmove
global _jit_setlength_memory
global memset
global _jit_print_int
global _jit_print_text
global _jit_print_newline
global _jit_print_double
global _jit_print_char
global _jit_dynstring_setlength
global _jit_dynstring_from_cstr
global _jit_dynstring_length
global _jit_dynstring_concat
global _jit_dynstring_copy
global _jit_dynstring_pos
global _jit_print_variant
global _jit_print_variant_array
global _jit_args_init
global _jit_args_shutdown
global _jit_param_count
global _jit_param_str_cstr
global _jit_command_line_cstr
global _jit_new_memory
global _jit_dispose_memory
global _jit_malloc
global _jit_calloc
global _jit_realloc
global _jit_free
global _jit_strdup
global _jit_strlen
global _jit_error_divide_by_zero
global _jit_locale_user
global _jit_locale_system
global _jit_ExitProcess
global _jit_GetCommandLineA
global _jit_object_instance_new
global _jit_object_instance_free
global _jit_object_free
global _jit_object_class_type
global _jit_class_parent
global _jit_class_name
global _jit_class_instance_size
global _jit_inherits_from_class
global _jit_inherits_from_object
global _jit_get_virtual_vmt
global _jit_get_virtual_object
global _jit_object_error_set_hook
global _jit_object_error_last
global _jit_object_error_last_message
global _jit_object_error_clear
global _jit_strncpy
global _jit_printf
global _jit_snprintf
global _jit_vprintf
global _jit_vsnprintf
global strlen
global _jit_read_char
global crc16_init
global crc16_update
global crc16_final
global crc32_init
global crc32_update
global crc32_final
global crc32c_init
global crc32c_update
global crc32c_final
global _jit_md5_init
global _jit_md5_update
global _jit_md5_final
global sha1_init
global sha1_update
global sha1_final
global sha3_init
global sha3_update
global sha3_final
global sha224_init
global sha224_update
global sha224_final
global sha256_init
global sha256_update
global sha256_final
global sha384_init
global sha384_update
global sha384_final
global sha512_init
global sha512_update
global sha512_final
global ExitProcess@4
global GetCommandLineA@0
global GetDiskFreeSpaceA@20
global GetDiskFreeSpaceExA@16
global GetDriveTypeA@4
global GetVolumeInformationA@32
global LoadLibraryA@4
global MessageBoxA@16
global SetLastError@4
global GetLastError@0
global GetProcAddress@8
global GetStdHandle@4
global ReadFile@20
global WriteFile@20
global WNetGetConnectionA@12
global _jit_raise
global crc64_init
global crc64_update
global blake2s_init
global blake2s_update
global blake2s_final
global _Z24_jit_error_out_of_memoryv
global _Z23_jit_error_array_boundsPKciii
global _Z22_jit_error_nil_pointerPKc
global _Z18_jit_set_exceptionP10JitContextPKc

_jit_dynarray_setlength:
    jmp dword [_dbm_runtime_proc_table + 4]

_jit_read_int:
    jmp dword [_dbm_runtime_proc_table + 8]

_jit_read_string:
    jmp dword [_dbm_runtime_proc_table + 12]

_jit_blake2:
    jmp dword [_dbm_runtime_proc_table + 16]

_jit_crc16:
    jmp dword [_dbm_runtime_proc_table + 20]

_jit_crc32:
    jmp dword [_dbm_runtime_proc_table + 24]

_jit_crc32c:
    jmp dword [_dbm_runtime_proc_table + 28]

_jit_crc64:
    jmp dword [_dbm_runtime_proc_table + 32]

_jit_md5:
    jmp dword [_dbm_runtime_proc_table + 36]

_jit_sha1:
    jmp dword [_dbm_runtime_proc_table + 40]

_jit_sha3:
    jmp dword [_dbm_runtime_proc_table + 44]

_jit_sha224:
    jmp dword [_dbm_runtime_proc_table + 48]

_jit_sha256:
    jmp dword [_dbm_runtime_proc_table + 52]

_jit_sha384:
    jmp dword [_dbm_runtime_proc_table + 56]

_jit_sha512:
    jmp dword [_dbm_runtime_proc_table + 60]

_jit_debug_break:
    jmp dword [_dbm_runtime_proc_table + 64]

_jit_disk_free:
    jmp dword [_dbm_runtime_proc_table + 68]

_jit_disk_total:
    jmp dword [_dbm_runtime_proc_table + 72]

_jit_disk_label:
    jmp dword [_dbm_runtime_proc_table + 76]

_jit_disk_serial:
    jmp dword [_dbm_runtime_proc_table + 80]

_jit_disk_filesystem:
    jmp dword [_dbm_runtime_proc_table + 84]

_jit_disk_type:
    jmp dword [_dbm_runtime_proc_table + 88]

_jit_disk_share:
    jmp dword [_dbm_runtime_proc_table + 92]

_jit_disk_used:
    jmp dword [_dbm_runtime_proc_table + 96]

_jit_disk_exists:
    jmp dword [_dbm_runtime_proc_table + 100]

_jit_disk_ready:
    jmp dword [_dbm_runtime_proc_table + 104]

_jit_disk_is_cdrom:
    jmp dword [_dbm_runtime_proc_table + 108]

_jit_disk_is_network:
    jmp dword [_dbm_runtime_proc_table + 112]

_jit_disk_is_removable:
    jmp dword [_dbm_runtime_proc_table + 116]

_jit_disk_is_fixed:
    jmp dword [_dbm_runtime_proc_table + 120]

_jit_error_runtime:
    jmp dword [_dbm_runtime_proc_table + 124]

_jit_error_array_bounds:
    jmp dword [_dbm_runtime_proc_table + 128]

_jit_error_string_range:
    jmp dword [_dbm_runtime_proc_table + 132]

_jit_error_nil_pointer:
    jmp dword [_dbm_runtime_proc_table + 136]

_jit_error_out_of_memory:
    jmp dword [_dbm_runtime_proc_table + 140]

_jit_exception_push:
    jmp dword [_dbm_runtime_proc_table + 144]

_jit_exception_pop:
    jmp dword [_dbm_runtime_proc_table + 148]

_jit_setjmp:
    jmp dword [_dbm_runtime_proc_table + 152]

_jit_longjmp:
    jmp dword [_dbm_runtime_proc_table + 156]

_jit_memcpy:
    jmp dword [_dbm_runtime_proc_table + 160]

_jit_memset:
    jmp dword [_dbm_runtime_proc_table + 164]

_jit_memcmp:
    jmp dword [_dbm_runtime_proc_table + 168]

_jit_memmove:
    jmp dword [_dbm_runtime_proc_table + 172]

_jit_setlength_memory:
    jmp dword [_dbm_runtime_proc_table + 176]

memset:
    jmp dword [_dbm_runtime_proc_table + 180]

_jit_print_int:
    jmp dword [_dbm_runtime_proc_table + 184]

_jit_print_text:
    jmp dword [_dbm_runtime_proc_table + 188]

_jit_print_newline:
    jmp dword [_dbm_runtime_proc_table + 192]

_jit_print_double:
    jmp dword [_dbm_runtime_proc_table + 196]

_jit_print_char:
    jmp dword [_dbm_runtime_proc_table + 200]

_jit_dynstring_setlength:
    jmp dword [_dbm_runtime_proc_table + 204]

_jit_dynstring_from_cstr:
    jmp dword [_dbm_runtime_proc_table + 208]

_jit_dynstring_length:
    jmp dword [_dbm_runtime_proc_table + 212]

_jit_dynstring_concat:
    jmp dword [_dbm_runtime_proc_table + 216]

_jit_dynstring_copy:
    jmp dword [_dbm_runtime_proc_table + 220]

_jit_dynstring_pos:
    jmp dword [_dbm_runtime_proc_table + 224]

_jit_print_variant:
    jmp dword [_dbm_runtime_proc_table + 228]

_jit_print_variant_array:
    jmp dword [_dbm_runtime_proc_table + 232]

_jit_args_init:
    jmp dword [_dbm_runtime_proc_table + 236]

_jit_args_shutdown:
    jmp dword [_dbm_runtime_proc_table + 240]

_jit_param_count:
    jmp dword [_dbm_runtime_proc_table + 244]

_jit_param_str_cstr:
    jmp dword [_dbm_runtime_proc_table + 248]

_jit_command_line_cstr:
    jmp dword [_dbm_runtime_proc_table + 252]

_jit_new_memory:
    jmp dword [_dbm_runtime_proc_table + 256]

_jit_dispose_memory:
    jmp dword [_dbm_runtime_proc_table + 260]

_jit_malloc:
    jmp dword [_dbm_runtime_proc_table + 264]

_jit_calloc:
    jmp dword [_dbm_runtime_proc_table + 268]

_jit_realloc:
    jmp dword [_dbm_runtime_proc_table + 272]

_jit_free:
    jmp dword [_dbm_runtime_proc_table + 276]

_jit_strdup:
    jmp dword [_dbm_runtime_proc_table + 280]

_jit_strlen:
    jmp dword [_dbm_runtime_proc_table + 284]

_jit_error_divide_by_zero:
    jmp dword [_dbm_runtime_proc_table + 288]

_jit_locale_user:
    jmp dword [_dbm_runtime_proc_table + 292]

_jit_locale_system:
    jmp dword [_dbm_runtime_proc_table + 296]

_jit_ExitProcess:
    jmp dword [_dbm_runtime_proc_table + 300]

_jit_GetCommandLineA:
    jmp dword [_dbm_runtime_proc_table + 304]

_jit_object_instance_new:
    jmp dword [_dbm_runtime_proc_table + 308]

_jit_object_instance_free:
    jmp dword [_dbm_runtime_proc_table + 312]

_jit_object_free:
    jmp dword [_dbm_runtime_proc_table + 316]

_jit_object_class_type:
    jmp dword [_dbm_runtime_proc_table + 320]

_jit_class_parent:
    jmp dword [_dbm_runtime_proc_table + 324]

_jit_class_name:
    jmp dword [_dbm_runtime_proc_table + 328]

_jit_class_instance_size:
    jmp dword [_dbm_runtime_proc_table + 332]

_jit_inherits_from_class:
    jmp dword [_dbm_runtime_proc_table + 336]

_jit_inherits_from_object:
    jmp dword [_dbm_runtime_proc_table + 340]

_jit_get_virtual_vmt:
    jmp dword [_dbm_runtime_proc_table + 344]

_jit_get_virtual_object:
    jmp dword [_dbm_runtime_proc_table + 348]

_jit_object_error_set_hook:
    jmp dword [_dbm_runtime_proc_table + 352]

_jit_object_error_last:
    jmp dword [_dbm_runtime_proc_table + 356]

_jit_object_error_last_message:
    jmp dword [_dbm_runtime_proc_table + 360]

_jit_object_error_clear:
    jmp dword [_dbm_runtime_proc_table + 364]

_jit_strncpy:
    jmp dword [_dbm_runtime_proc_table + 368]

_jit_printf:
    jmp dword [_dbm_runtime_proc_table + 372]

_jit_snprintf:
    jmp dword [_dbm_runtime_proc_table + 376]

_jit_vprintf:
    jmp dword [_dbm_runtime_proc_table + 380]

_jit_vsnprintf:
    jmp dword [_dbm_runtime_proc_table + 384]

strlen:
    jmp dword [_dbm_runtime_proc_table + 388]

_jit_read_char:
    jmp dword [_dbm_runtime_proc_table + 392]

crc16_init:
    jmp dword [_dbm_runtime_proc_table + 396]

crc16_update:
    jmp dword [_dbm_runtime_proc_table + 400]

crc16_final:
    jmp dword [_dbm_runtime_proc_table + 404]

crc32_init:
    jmp dword [_dbm_runtime_proc_table + 408]

crc32_update:
    jmp dword [_dbm_runtime_proc_table + 412]

crc32_final:
    jmp dword [_dbm_runtime_proc_table + 416]

crc32c_init:
    jmp dword [_dbm_runtime_proc_table + 420]

crc32c_update:
    jmp dword [_dbm_runtime_proc_table + 424]

crc32c_final:
    jmp dword [_dbm_runtime_proc_table + 428]

_jit_md5_init:
    jmp dword [_dbm_runtime_proc_table + 432]

_jit_md5_update:
    jmp dword [_dbm_runtime_proc_table + 436]

_jit_md5_final:
    jmp dword [_dbm_runtime_proc_table + 440]

sha1_init:
    jmp dword [_dbm_runtime_proc_table + 444]

sha1_update:
    jmp dword [_dbm_runtime_proc_table + 448]

sha1_final:
    jmp dword [_dbm_runtime_proc_table + 452]

sha3_init:
    jmp dword [_dbm_runtime_proc_table + 456]

sha3_update:
    jmp dword [_dbm_runtime_proc_table + 460]

sha3_final:
    jmp dword [_dbm_runtime_proc_table + 464]

sha224_init:
    jmp dword [_dbm_runtime_proc_table + 468]

sha224_update:
    jmp dword [_dbm_runtime_proc_table + 472]

sha224_final:
    jmp dword [_dbm_runtime_proc_table + 476]

sha256_init:
    jmp dword [_dbm_runtime_proc_table + 480]

sha256_update:
    jmp dword [_dbm_runtime_proc_table + 484]

sha256_final:
    jmp dword [_dbm_runtime_proc_table + 488]

sha384_init:
    jmp dword [_dbm_runtime_proc_table + 492]

sha384_update:
    jmp dword [_dbm_runtime_proc_table + 496]

sha384_final:
    jmp dword [_dbm_runtime_proc_table + 500]

sha512_init:
    jmp dword [_dbm_runtime_proc_table + 504]

sha512_update:
    jmp dword [_dbm_runtime_proc_table + 508]

sha512_final:
    jmp dword [_dbm_runtime_proc_table + 512]

ExitProcess@4:
    jmp dword [_dbm_runtime_proc_table + 516]

GetCommandLineA@0:
    jmp dword [_dbm_runtime_proc_table + 520]

GetDiskFreeSpaceA@20:
    jmp dword [_dbm_runtime_proc_table + 524]

GetDiskFreeSpaceExA@16:
    jmp dword [_dbm_runtime_proc_table + 528]

GetDriveTypeA@4:
    jmp dword [_dbm_runtime_proc_table + 532]

GetVolumeInformationA@32:
    jmp dword [_dbm_runtime_proc_table + 536]

LoadLibraryA@4:
    jmp dword [_dbm_runtime_proc_table + 540]

MessageBoxA@16:
    jmp dword [_dbm_runtime_proc_table + 544]

SetLastError@4:
    jmp dword [_dbm_runtime_proc_table + 548]

GetLastError@0:
    jmp dword [_dbm_runtime_proc_table + 552]

GetProcAddress@8:
    jmp dword [_dbm_runtime_proc_table + 556]

GetStdHandle@4:
    jmp dword [_dbm_runtime_proc_table + 560]

ReadFile@20:
    jmp dword [_dbm_runtime_proc_table + 564]

WriteFile@20:
    jmp dword [_dbm_runtime_proc_table + 568]

WNetGetConnectionA@12:
    jmp dword [_dbm_runtime_proc_table + 572]

_jit_raise:
    jmp dword [_dbm_runtime_proc_table + 576]

crc64_init:
    jmp dword [_dbm_runtime_proc_table + 580]

crc64_update:
    jmp dword [_dbm_runtime_proc_table + 584]

blake2s_init:
    jmp dword [_dbm_runtime_proc_table + 588]

blake2s_update:
    jmp dword [_dbm_runtime_proc_table + 592]

blake2s_final:
    jmp dword [_dbm_runtime_proc_table + 596]

_Z24_jit_error_out_of_memoryv:
    jmp dword [_dbm_runtime_proc_table + 600]

_Z23_jit_error_array_boundsPKciii:
    jmp dword [_dbm_runtime_proc_table + 604]

_Z22_jit_error_nil_pointerPKc:
    jmp dword [_dbm_runtime_proc_table + 608]

_Z18_jit_set_exceptionP10JitContextPKc:
    jmp dword [_dbm_runtime_proc_table + 612]
