;; ---------------------------------------------------------------------------
;; AUTO-GENERATED by make_dll_runtime_thunks.py
;; Do not edit manually.
;; ---------------------------------------------------------------------------
bits 32

section .text

extern _dbm_runtime_proc_table

global _jit_dynarray_setlength
global _jit_read_int
global _jit_read_string

global _jit_print_int
global _jit_print_text
global _jit_print_newline
global _jit_print_double
global _jit_print_char
global _jit_dynstring_setlength
global _jit_dynstring_from_cstr
global _jit_dynstring_length
global _jit_dynstring_concat
global _jit_dynstring_copy
global _jit_dynstring_pos
global _jit_print_variant
global _jit_print_variant_array


global _jit_error_runtime
global _jit_error_array_bounds
global _jit_error_string_range
global _jit_error_nil_pointer
global _jit_error_out_of_memory
global _jit_exception_push
global _jit_exception_pop
global _jit_setjmp
global _jit_longjmp
global _jit_memcpy
global _jit_memset
global _jit_memcmp
global _jit_memmove
global _jit_setlength_memory
global memset

global _jit_args_init
global _jit_args_shutdown
global _jit_param_count
global _jit_param_str_cstr
global _jit_command_line_cstr
global _jit_new_memory
global _jit_dispose_memory
global _jit_malloc
global _jit_calloc
global _jit_realloc
global _jit_free
global _jit_strdup
global _jit_strlen
global _jit_error_divide_by_zero
global _jit_locale_user
global _jit_locale_system
global _jit_ExitProcess
global _jit_GetCommandLineA

global _jit_object_instance_new
global _jit_object_instance_free
global _jit_object_free
global _jit_object_class_type
global _jit_class_parent
global _jit_class_name
global _jit_class_instance_size
global _jit_inherits_from_class
global _jit_inherits_from_object
global _jit_get_virtual_vmt
global _jit_get_virtual_object
global _jit_object_error_set_hook
global _jit_object_error_last
global _jit_object_error_last_message
global _jit_object_error_clear

global _jit_strncpy
global _jit_printf
global _jit_snprintf
global _jit_vprintf
global _jit_vsnprintf
global strlen
global _jit_read_char

global _jit_raise

global _Z24_jit_error_out_of_memoryv
global _Z23_jit_error_array_boundsPKciii
global _Z22_jit_error_nil_pointerPKc
global _Z18_jit_set_exceptionP10JitContextPKc

_jit_print_int:
    jmp dword [_dbm_runtime_proc_table + 184]

_jit_print_text:
    jmp dword [_dbm_runtime_proc_table + 188]

_jit_print_newline:
    jmp dword [_dbm_runtime_proc_table + 192]

_jit_print_double:
    jmp dword [_dbm_runtime_proc_table + 196]

_jit_print_char:
    jmp dword [_dbm_runtime_proc_table + 200]

_jit_dynstring_setlength:
    jmp dword [_dbm_runtime_proc_table + 204]

_jit_dynstring_from_cstr:
    jmp dword [_dbm_runtime_proc_table + 208]

_jit_dynstring_length:
    jmp dword [_dbm_runtime_proc_table + 212]

_jit_dynstring_concat:
    jmp dword [_dbm_runtime_proc_table + 216]

_jit_dynstring_copy:
    jmp dword [_dbm_runtime_proc_table + 220]

_jit_dynstring_pos:
    jmp dword [_dbm_runtime_proc_table + 224]

_jit_print_variant:
    jmp dword [_dbm_runtime_proc_table + 228]

_jit_print_variant_array:
    jmp dword [_dbm_runtime_proc_table + 232]





_jit_dynarray_setlength:
    jmp dword [_dbm_runtime_proc_table + 4]

_jit_read_int:
    jmp dword [_dbm_runtime_proc_table + 8]

_jit_read_string:
    jmp dword [_dbm_runtime_proc_table + 12]

_jit_debug_break:
    jmp dword [_dbm_runtime_proc_table + 64]



_jit_error_runtime:
    jmp dword [_dbm_runtime_proc_table + 124]

_jit_error_array_bounds:
    jmp dword [_dbm_runtime_proc_table + 128]

_jit_error_string_range:
    jmp dword [_dbm_runtime_proc_table + 132]

_jit_error_nil_pointer:
    jmp dword [_dbm_runtime_proc_table + 136]

_jit_error_out_of_memory:
    jmp dword [_dbm_runtime_proc_table + 140]

_jit_exception_push:
    jmp dword [_dbm_runtime_proc_table + 144]

_jit_exception_pop:
    jmp dword [_dbm_runtime_proc_table + 148]

_jit_setjmp:
    jmp dword [_dbm_runtime_proc_table + 152]

_jit_longjmp:
    jmp dword [_dbm_runtime_proc_table + 156]

_jit_memcpy:
    jmp dword [_dbm_runtime_proc_table + 160]

_jit_memset:
    jmp dword [_dbm_runtime_proc_table + 164]

_jit_memcmp:
    jmp dword [_dbm_runtime_proc_table + 168]

_jit_memmove:
    jmp dword [_dbm_runtime_proc_table + 172]

_jit_setlength_memory:
    jmp dword [_dbm_runtime_proc_table + 176]

memset:
    jmp dword [_dbm_runtime_proc_table + 180]


_jit_args_init:
    jmp dword [_dbm_runtime_proc_table + 236]

_jit_args_shutdown:
    jmp dword [_dbm_runtime_proc_table + 240]

_jit_param_count:
    jmp dword [_dbm_runtime_proc_table + 244]

_jit_param_str_cstr:
    jmp dword [_dbm_runtime_proc_table + 248]

_jit_command_line_cstr:
    jmp dword [_dbm_runtime_proc_table + 252]

_jit_new_memory:
    jmp dword [_dbm_runtime_proc_table + 256]

_jit_dispose_memory:
    jmp dword [_dbm_runtime_proc_table + 260]

_jit_malloc:
    jmp dword [_dbm_runtime_proc_table + 264]

_jit_calloc:
    jmp dword [_dbm_runtime_proc_table + 268]

_jit_realloc:
    jmp dword [_dbm_runtime_proc_table + 272]

_jit_free:
    jmp dword [_dbm_runtime_proc_table + 276]

_jit_strdup:
    jmp dword [_dbm_runtime_proc_table + 280]

_jit_strlen:
    jmp dword [_dbm_runtime_proc_table + 284]

_jit_error_divide_by_zero:
    jmp dword [_dbm_runtime_proc_table + 288]

_jit_locale_user:
    jmp dword [_dbm_runtime_proc_table + 292]

_jit_locale_system:
    jmp dword [_dbm_runtime_proc_table + 296]

_jit_ExitProcess:
    jmp dword [_dbm_runtime_proc_table + 300]

_jit_GetCommandLineA:
    jmp dword [_dbm_runtime_proc_table + 304]

_jit_object_instance_new:
    jmp dword [_dbm_runtime_proc_table + 308]

_jit_object_instance_free:
    jmp dword [_dbm_runtime_proc_table + 312]

_jit_object_free:
    jmp dword [_dbm_runtime_proc_table + 316]

_jit_object_class_type:
    jmp dword [_dbm_runtime_proc_table + 320]

_jit_class_parent:
    jmp dword [_dbm_runtime_proc_table + 324]

_jit_class_name:
    jmp dword [_dbm_runtime_proc_table + 328]

_jit_class_instance_size:
    jmp dword [_dbm_runtime_proc_table + 332]

_jit_inherits_from_class:
    jmp dword [_dbm_runtime_proc_table + 336]

_jit_inherits_from_object:
    jmp dword [_dbm_runtime_proc_table + 340]

_jit_get_virtual_vmt:
    jmp dword [_dbm_runtime_proc_table + 344]

_jit_get_virtual_object:
    jmp dword [_dbm_runtime_proc_table + 348]

_jit_object_error_set_hook:
    jmp dword [_dbm_runtime_proc_table + 352]

_jit_object_error_last:
    jmp dword [_dbm_runtime_proc_table + 356]

_jit_object_error_last_message:
    jmp dword [_dbm_runtime_proc_table + 360]

_jit_object_error_clear:
    jmp dword [_dbm_runtime_proc_table + 364]


_jit_strncpy:
    jmp dword [_dbm_runtime_proc_table + 368]

_jit_printf:
    jmp dword [_dbm_runtime_proc_table + 372]

_jit_snprintf:
    jmp dword [_dbm_runtime_proc_table + 376]

_jit_vprintf:
    jmp dword [_dbm_runtime_proc_table + 380]

_jit_vsnprintf:
    jmp dword [_dbm_runtime_proc_table + 384]

strlen:
    jmp dword [_dbm_runtime_proc_table + 388]

_jit_read_char:
    jmp dword [_dbm_runtime_proc_table + 392]


_jit_raise:
    jmp dword [_dbm_runtime_proc_table + 576]


_Z24_jit_error_out_of_memoryv:
    jmp dword [_dbm_runtime_proc_table + 600]

_Z23_jit_error_array_boundsPKciii:
    jmp dword [_dbm_runtime_proc_table + 604]

_Z22_jit_error_nil_pointerPKc:
    jmp dword [_dbm_runtime_proc_table + 608]

_Z18_jit_set_exceptionP10JitContextPKc:
    jmp dword [_dbm_runtime_proc_table + 612]
