#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path


def load_runtime_imports(path: Path):
    spec = importlib.util.spec_from_file_location(
        "dbm_runtime_imports",
        path
    )

    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    class ImportContainer:
        imports = {}

    container = ImportContainer()
    module.initialize_commondata_imports(container)

    matches = []

    for dll_name, items in container.imports.items():
        normalized = Path(str(dll_name)).name.lower()

        if normalized in {
            "libdbase2many.32.dll",
            "libdbase2many.132.dll",
        }:
            matches.extend(items)

    if not matches:
        raise RuntimeError(
            "runtime DLL import table not found"
        )

    result = []
    seen_ordinals = set()
    seen_names = set()

    for symbol, ordinal in matches:
        ordinal = int(ordinal)
        symbol = str(symbol)

        if ordinal in seen_ordinals:
            raise RuntimeError(
                f"duplicate runtime ordinal: {ordinal}"
            )

        if symbol in seen_names:
            raise RuntimeError(
                f"duplicate runtime symbol: {symbol}"
            )

        seen_ordinals.add(ordinal)
        seen_names.add(symbol)
        result.append((symbol, ordinal))

    result.sort(key=lambda item: item[1])

    expected = list(
        range(1, result[-1][1] + 1)
    )
    actual = [ordinal for _, ordinal in result]

    if actual != expected:
        raise RuntimeError(
            "runtime ordinals must form a continuous range "
            f"1..{result[-1][1]}"
        )

    return result


def write_asm(path: Path, entries):
    lines = [
        ";; ---------------------------------------------------------------------------",
        ";; AUTO-GENERATED by make_dll_runtime_thunks.py",
        ";; Do not edit manually.",
        ";; ---------------------------------------------------------------------------",
        "bits 32",
        "",
        "section .text",
        "",
        "extern _dbm_runtime_proc_table",
        "",
    ]

    for symbol, _ in entries:
        lines.append(f"global {symbol}")

    lines.append("")

    for symbol, ordinal in entries:
        lines.extend([
            f"{symbol}:",
            (
                "    jmp dword "
                f"[_dbm_runtime_proc_table + {ordinal * 4}]"
            ),
            "",
        ])

    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
        newline="\n"
    )


def write_header(path: Path, max_ordinal: int):
    path.write_text(
        "\n".join([
            "// AUTO-GENERATED by make_dll_runtime_thunks.py",
            "#ifndef DBASE2MANY_RUNTIME_ORDINALS_H",
            "#define DBASE2MANY_RUNTIME_ORDINALS_H",
            "",
            f"#define DBM_RUNTIME_MAX_ORDINAL {max_ordinal}",
            "",
            "#endif",
            "",
        ]),
        encoding="utf-8",
        newline="\n"
    )


def main() -> int:
    base = Path(__file__).resolve().parent

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--imports",
        type=Path,
        default=(
            base.parent
            / "compiler"
            / "common"
            / "runtime_imports.py"
        )
    )
    parser.add_argument(
        "--asm",
        type=Path,
        default=base / "dll_runtime_thunks.asm"
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=base / "dll_runtime_ordinals.h"
    )
    args = parser.parse_args()

    entries = load_runtime_imports(
        args.imports.resolve()
    )

    write_asm(
        args.asm.resolve(),
        entries
    )
    write_header(
        args.header.resolve(),
        entries[-1][1]
    )

    print(
        f"generated {len(entries)} runtime thunks "
        f"for ordinals 1..{entries[-1][1]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
