# ---------------------------------------------------------------------------
# Author: (c) 2024, 2025, 2026 Jens Kallup - paule32
# All rights reserved
# ---------------------------------------------------------------------------
name: onedir-release-pascal

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        default: "v0.0.1"
        type: string
      python_version:
        required: true
        default: "3.14"
        type: string
      java_version:
        required: true
        default: "17"
        type: string
      antlr_tool_version:
        required: true
        default: "4.13.2"
        type: string
      antlr_runtime_version:
        required: true
        default: "4.13.2"
        type: string

  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      python_version:
        required: true
        type: string
      java_version:
        required: true
        type: string
      antlr_tool_version:
        required: true
        type: string
      antlr_runtime_version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/release-build.yml
    with:
      tag: ${{ inputs.tag }}
      build_mode: onedir
      language: pascal
      python_version: ${{ inputs.python_version }}
      java_version: ${{ inputs.java_version }}
      antlr_tool_version: ${{ inputs.antlr_tool_version }}
      antlr_runtime_version: ${{ inputs.antlr_runtime_version }}
    secrets: inherit
